name: ESLint and Jest

on:
  pull_request:
    branches:
      - "*"

jobs:
  eslint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.yarnpkg.com"

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn run eslint .

      - name: Run Jest
        run: yarn run test
